language: node_js
node_js:
  - "8"
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
    - "~/.npm"
env:
  global:
    - JOBS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_08c3bef10003_key -iv $encrypted_08c3bef10003_iv
    -in traviskey.enc -out ~\/traviskey -d
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --non-interactive
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then bash ./deployToProduction.sh; fi
